/**
 * Created by florinpopa on 03/07/2018.
 */
export default {
    UNKNOWN_ERROR: {type: "Unknown error", message: 'The operation failed. Please verify the data entered and try again'},
    ERROR_LOGIN: {type: "Login error", message: 'An error occurred while trying to login'},
    ERROR_GET_USER: {type: "User error", message: 'An error occurred while trying to get user data'},
    ERROR_OUTBREAK: {type: "Outbreak error", message: 'An error occurred while trying to get outbreak data'},
    ERROR_FOLLOWUPS: {type: "Follow-ups error", message: 'An error occurred while trying to get follow-ups data'},
    ERROR_UPDATE_FOLLOWUP: {type: "Follow-up update error", message: 'An error occurred while trying to update the follow-up'},
    ERROR_DELETE_FOLLOWUP: {type: "Follow-up delete error", message: 'An error occurred while trying to delete the follow-up'},
    ERROR_CONTACT: {type: "Contacts error", message: 'An error occurred while trying to get contacts data'},
    ERROR_UPDATE_CONTACT: {type: "Contact update error", message: 'An error occurred while trying to update the contact'},
    ERROR_CASES: {type: "Cases error", message: 'An error occurred while trying to get cases data'},
    ERROR_EVENTS: {type: "Events error", message: 'An error occurred while trying to get events data'},
    ERROR_REFERENCE_DATA: {type: "Reference data error", message: 'An error occurred while trying to get reference data'},
}